=== DEFRA/stw-mapping-library/trade-schema/src/main/resources/json/uncefact/definitions/SpsAuthenticationType.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "SpsAuthenticationType.json",
  "type": "object",
  "properties": {
    "actualDateTime": {
      "$ref": "DateTimeType.json"
    },
    "includedSpsClause": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "content": {
            "type": "array",
            "items": {
              "allOf": [
                {
                  "$ref": "TextType.json"
                },
                {
                  "required": [
                    "value"
                  ]
                }
              ]
            }
          },
          "id": {
            "$ref": "IDType.json"
          }
        },
        "required": [
          "content"
        ]
      }
    },
    "issueSpsLocation": {
      "$ref": "SpsLocationType.json"
    },
    "locationProviderSpsParty": {
      "$ref": "SpsPartyType.json"
    },
    "providerSpsParty": {
      "$ref": "SpsPartyType.json"
    },
    "typeCode": {
      "$ref": "GovernmentActionCodeType.json"
    }
  },
  "required": [
    "actualDateTime",
    "includedSpsClause",
    "providerSpsParty"
  ]
}

=== DEFRA/stw-mapping-library/trade-mapping-to-trade/src/test/resources/mapping/chedpp/spsexchangeddocument/spsAuthenticationTypeForClearanceComplete.json
{
  "actualDateTime" : {
    "dateTime" : {
      "value" : "2020-08-12T12:20:46Z"
    }
  },
  "includedSpsClause" : [ {
    "content" : [ {
      "value" : "DefraTestBIP@anthunt3.33mail.com"
    } ],
    "id" : {
      "value" : "SIGNATORY_PERSON_EMAIL"
    }
  } ],
  "providerSpsParty" : {
    "roleCode" : {
      "value" : "AM"
    },
    "specifiedSpsPerson" : {
      "name" : {
        "value" : "Percy Inspector-Tester"
      }
    },
    "typeCode" : [ {
      "value" : "AUTHORITY"
    } ]
  },
  "typeCode" : {
    "value" : "1"
  }
}

=== DEFRA/stw-mapping-library/trade-mapping-to-trade/src/test/resources/mapping/chedpp/spsexchangeddocument/spsAuthenticationTypeForInspectionComplete.json
{
  "actualDateTime" : {
    "dateTime" : {
      "value" : "2019-11-29T11:02:28Z"
    }
  },
  "includedSpsClause" : [ {
    "content" : [ {
      "value" : "#{contentType}"
    } ],
    "id" : {
      "value" : "PURPOSE"
    }
  }, {
    "content" : [ {
      "value" : "DefraTestBIP@anthunt3.33mail.com"
    } ],
    "id" : {
      "value" : "SIGNATORY_PERSON_EMAIL"
    }
  } ],
  "providerSpsParty" : {
    "id" : {
      "value" : "79f6dc68-2144-e911-a96a-000d3a29ba60"
    },
    "name" : {
      "value" : "Defra Test BIP"
    },
    "roleCode" : {
      "value" : "VJ"
    },
    "specifiedSpsAddress" : {
      "cityName" : {
        "value" : "Surrey"
      },
      "countryID" : {
        "value" : "GB"
      },
      "lineOne" : {
        "value" : "Animal and Plant Health Agency, Woodham Lane, New Haw, Addlestone, Surrey, KT15 3NB, GB"
      }
    },
    "specifiedSpsPerson" : {
      "name" : {
        "value" : "Percy Inspector-Tester"
      }
    },
    "typeCode" : [ {
      "value" : "OPERATOR"
    } ]
  },
  "typeCode" : {
    "value" : "4"
  }
}
